name: エンジニアHub Next 13

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  TZ: Asia/Tokyo

permissions:
  contents: read

jobs:
  en_hub_next_ci:
    name: en_hub_next
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: （デバッグ用）Payload ($GITHUB_EVENT_PATH) を確認する
        run: |
          cat $GITHUB_EVENT_PATH
      - name: $ git clone する
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: bun のセットアップを行う
        # https://github.com/oven-sh/setup-bun/releases
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        # with:
        #   bun-version: 1.2.8 # or "latest", "canary", <sha>
      - name: Node.js のセットアップを行う
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .node-version
      - name: package.json の依存関係をインストールする ($ bun install)
        run: |
          bun install --frozen-lockfile
      - name: ビルドを行う ($ bun run build)
        run: |
          bun run build
